<footer class="footer" role="contentinfo">
    <div class="container">
        <ul class="footer-nav">
            <li class="footer-nav__item"><a href="/" class="footer-nav__link">на главную</a></li>
            <li class="footer-nav__item"><a href="catalog.php" class="footer-nav__link">каталог товаров</a></li>
            <li class="footer-nav__item"><a href="#" class="footer-nav__link">инструкции по укладке</a></li>
            <li class="footer-nav__item"><a href="#" class="footer-nav__link">доставка</a></li>
            <li class="footer-nav__item"><a href="#" class="footer-nav__link">партнёры</a></li>
            <li class="footer-nav__item"><a href="contact.php" class="footer-nav__link">контакты</a></li>
        </ul>

        <ul class="social-list">
            <li class="social-list__item fb"><a href="#"></a></li>
            <li class="social-list__item odn"><a href="#"></a></li>
            <li class="social-list__item vk"><a href="#"></a></li>
        </ul>
        
        <div class="copyright">2010-2015 &copy; <a href="http://www.parquet.od.ua">parquet.od.ua</a>, Все права защищены.</div>
        
        <div class="f-logo">
            <a href="#">
                <img src="/images/design/logo_mini.png" alt="Паркетный салон">
            </a>
        </div>

    </div>
</footer><!-- end .footer -->