<nav class="main-menu" role="navigation">
    <div class="container">
        <ul class="main-menu__list">
            <li><a href="/">на главную</a></li>
            <li><a href="/catalog">каталог товаров</a></li>
            <li><a href="#">инструкции по укладке</a></li>
            <li><a href="#">доставка</a></li>
            <li><a href="#">партнёры</a></li>
            <li><a href="/contact.php">контакты</a></li>
        </ul>

        <div class="worktime">с <span>10:00</span> до <span>21:00</span></div>
</nav><!-- end .main-menu -->